name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_player_iframe plugin.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  youtube_player_iframe: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^2.3.1
  yaml: ^3.1.1
  golden_toolkit: ^0.13.0


flutter:
  uses-material-design: true
